normalization:
  no_mean_norm: false
  std_norm: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

training:
  batch_size: 16
  lr: 0.001
  optimizer_type: 'adam'
  epochs: 200
  num_workers: 14
  train_crop: 'corner'
  sample_size: 224
  scales: [1.0, 0.8, 0.6]
  sample_duration: 8
  sensor_duration: 10
  downsample: 2
  norm_value: 255
  num_classes: 32
  modality: 'RGB'
  video_path: '../frames'
  annotation_path: '../Dynamic_Gesture_Dataset/data/annotations/versions/v1/annotation_all_balance.json'
  no_train: false
