normalization:
  no_mean_norm: false
  std_norm: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

training:
  batch_size: 16
  lr: 0.01
  epochs: 100
  num_workers: 4
  train_crop: 'random'
  sample_size: 224
  scales: [1.0, 0.8, 0.6]
  sample_duration: 8
  sensor_duration: 10
  downsample: 2
  norm_value: 255
  modality: 'RGB'
  video_path: ''
  annotation_path: ''
  no_train: false
